type Balance @entity {
  id: ID!
  amount: BigInt!
}

type Deposit @entity {
  id: ID!
  user: String!
  amount: BigInt!
  timestamp: Int!
}

type Call @entity {
  id: ID!
  consumer: String!
  provider: String!
  amount: BigInt!
  status: String!
  reservedAt: Int!
  finalizedAt: Int
  reserveTx: String!
  finalTx: String
}

type Withdrawal @entity {
  id: ID!
  user: String!
  amount: BigInt!
  timestamp: Int!
}

type OperatorChange @entity {
  id: ID!
  oldOperator: String!
  newOperator: String!
  timestamp: Int!
  txHash: String!
}
